### ISSUE TITLE
Question: It's possible to register multiple domains?

### ISSUE THREAD

**Issue by marek-hanzal** [n1b0r/docker-flow-proxy-letsencrypt#16]
...using `com.df.letsencrypt.host` ? For example:

` - com.df.letsencrypt.host=gitlab.example.com,docker.example.com` as the usecase is GitLab which needs one certificate for the instance itself and second for Docker Registry.

**Comment by n1b0r** [comment]
Hello,

Yes it is possible.

I'm currently running a gitlab instance with the following `docker-stack.yml` :

```
version: '3.3'
services:
  gitlab:
    image: gitlab/gitlab-ce:9.5.1-ce.0    
    ports:
      - 10022:22
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-config:/etc/gitlab
      - le-certs:/etc/gitlab/ssl
    networks:
      - proxy
    deploy:
      labels:
        - com.df.letsencrypt.email=email@domain.com
        - com.df.servicePath=/
        - com.df.srcPort=443
        - com.df.port=443
        - com.df.distribute=true
        - com.df.letsencrypt.host=git.domain.com,docker.domain.com
        - com.df.sslVerifyNone=true
        - com.df.notify=true
        - com.df.serviceDomain=git.domain.com,docker.domain.com
networks:
  proxy:
    external: true
volumes:
  gitlab-data:
    external: true
  le-certs:
    external: true
  gitlab-logs:
    external: true
  gitlab-config:
    external: true
```

Please tell me if you encounter any problem.
