### ISSUE TITLE
services via "docker stack deploy" ignored

### ISSUE THREAD

**Issue by eleaner** [n1b0r/docker-flow-proxy-letsencrypt#42]
Dear all,

works great for all services created via "docker service create" but all the services created via "docker stack deploy" are ignored

what am I doing wrong?

**Comment by n1b0r** [comment]
could you provide a working docker create command and a failing stack.yml file ?

**Comment by eleaner** [comment]
below proxy-net connects to proxy stack
working

```
docker service create --name seafile \
      --mount type=volume,source=liz_seafile,destination=/shared/seafile,volume-driver=liz \
      --env SEAFILE_ADMIN_EMAIL=xxxl \
      --env SEAFILE_ADMIN_PASSWORD=xxx \
      --env SEAFILE_SERVER_LETSENCRYPT=false \
      --env SEAFILE_SERVER_HOSTNAME=xx \
      --env DB_HOST=172.17.0.1 \
      --env DB_ROOT_PASSWD=xxx \
      --network proxy-net \
      --network mariadb-net \
      --network seafile_net \
      --label com.df.notify=true \
      --label com.df.distribute=true \
      --label com.df.letsencrypt.email=xxx \
      --label com.df.serviceDomain=xxx \
      --label com.df.servicePath=/ \
      --label com.df.srcPort=443 \
      --label com.df.port=80 \
      --label com.df.letsencrypt.host=xxx \
      -p 9990:80 \
docker.seadrive.org/seafileltd/seafile-pro-mc:7.0.8
```

not working
```
version: '3.6'
services:
[...]
  server:
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:7.0.8
    ports:
      - "9990:80"
    volumes:
      - liz_seafile:/shared/seafile  
    environment:
      - DB_HOST=172.17.0.1
      - DB_ROOT_PASSWD=xxx  
      - SEAFILE_ADMIN_EMAIL=xxxl
      - SEAFILE_ADMIN_PASSWORD=xxx
      - SEAFILE_SERVER_LETSENCRYPT=false 
      - SEAFILE_SERVER_HOSTNAME=xxx 
    labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.letsencrypt.email=xxx
      - com.df.serviceDomain=xxx
      - com.df.servicePath=/
      - com.df.srcPort=443
      - com.df.port=80
      - com.df.letsencrypt.host=xxx
    depends_on:
      - memcached
      - elasticsearch
    networks:
      - proxy-net
      - mariadb-net
      - net

networks:
  net:
  mariadb-net:
    external: true
  proxy-net:
    external: true
[...]
```
